=== vladmitroshin/knu-web-development/labs/schedule.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">

    <xs:element name="schedule" type="ScheduleType"/>
    <xs:element name="record" type="RecordType"/>
    <xs:element name="doctor" type="DoctorType"/>
    <xs:element name="week" type="WeekType"/>
    <xs:element name="day" type="DayType"/>

    <xs:complexType name="ScheduleType">
        <xs:sequence>
            <xs:element ref="record" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RecordType">
        <xs:sequence>
            <xs:element ref="doctor"/>

            <xs:element name="photo">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="src" type="xs:string"/>
                            <xs:attribute name="alt" type="xs:string" default="image"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>

            <xs:element ref="week"/>
            <xs:element name="speciality" type="xs:string" minOccurs="1"/>
            <xs:element name="office_number" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="DoctorType">
        <xs:sequence>
            <xs:element name="surname" type="xs:string" maxOccurs="1"/>
            <xs:element name="name" type="xs:string" maxOccurs="1"/>
            <xs:element name="patronymic" type="xs:string" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="WeekType">
        <xs:sequence>
            <xs:element ref="day" minOccurs="5" maxOccurs="5"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DayType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="class" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== vladmitroshin/knu-web-development/labs/schedule_xsd.xml
<?xml version="1.0"?>

<schedule xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com schedule.xsd">
    
    <record id="x1">
        <doctor>
            <surname>Иванов</surname>
            <name>Иван</name>
            <patronymic>Иванович</patronymic>
        </doctor>
        <photo src="image1.jpg" alt="image"></photo>
        <week>
            <day class="Monday">10:00-15:00</day>
            <day class="Tuesday">-</day>
            <day class="Wednesday">9:00-16:00</day>
            <day class="Thursday">-</day>
            <day class="Friday">14:00-17:00</day>
        </week>
        <speciality>Терапевт</speciality>
        <office_number>111</office_number>
    </record>

    <record id="x2">
        <doctor>
            <surname>Петров</surname>
            <name>Пётр</name>
            <patronymic>Петрович</patronymic>
        </doctor>
        <photo src="image2.jpg" alt="image"></photo>
        <week>
            <day class="Monday">12:00-16:00</day>
            <day class="Tuesday">8:00-13:00</day>
            <day class="Wednesday">-</day>
            <day class="Thursday">10:00-15:00</day>
            <day class="Friday">-</day>
        </week>
        <speciality>Невролог</speciality>
        <office_number>123</office_number>
    </record>

    <record id="x3">
        <doctor>
            <surname>Андреев</surname>
            <name>Андрей</name>
            <patronymic>Андреевич</patronymic>
        </doctor>
        <photo src="image3.jpg" alt="image"></photo>
        <week>
            <day class="Monday">-</day>
            <day class="Tuesday">10:00-14:00</day>
            <day class="Wednesday">9:00-16:00</day>
            <day class="Thursday">-</day>
            <day class="Friday">14:00-17:00</day>
        </week>
        <speciality>Кардиолог</speciality>
        <office_number>120</office_number>
    </record>

</schedule>
